## TWITTER
## https://python-twitter.readthedocs.io/en/latest/getting_started.html#getting-your-application-tokens
TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""

## MASTODON
## https://docs.joinmastodon.org/api/authentication/
MASTODON_CLIENT_ID = ""
MASTODON_CLIENT_SECRET = ""
MASTODON_ACCESS_TOKEN = ""
MASTODON_URL = ""
